.github/workflows/check.yml
.github/workflows/publish.yml
README.md
package-lock.json
package.json

- All PRs are required to pass the tests (+ linter/prettier if we add that as a command later)
- Creating releases can be done through the GitHub interface, which should auto-tag the latest master, update the package.json + publish to npm. The release should have a name like `v1.0.1` which will be used for the version. The description of the release can be used for a changelog.
I haven't tested the publish script - will do that once this PR is merged.

Add GitHub actions - for branch check and for publish

---

.gitignore
package-lock.json
package.json
spec/lib/helpers.ts
spec/separate-zod-instance.spec.ts
spec/simple.spec.ts
src/lib/zod-is-type.ts
src/openapi-generator.ts
src/openapi-registry.ts
src/zod-extensions.ts

Fixes https://github.com/asteasolutions/zod-to-openapi/issues/17 . See [my comment](https://github.com/asteasolutions/zod-to-openapi/issues/17#issuecomment-1159687818) for details on how this PR fixes it.

Fix usage from separate zod instances (fixing Next.js integration)

---

spec/simple.spec.ts

Added a test based on the description of Issue #16. Nullable is supported.

added tests for nullable and removing openapi props

---

src/index.ts

PR Example of what I am looking for.
closes #32

Expose the RouteConfig interface (proposal)

---

README.md
example/index.ts
jest.config.js
spec/custom-components.spec.ts
spec/polymorphism.spec.ts
spec/routes.spec.ts
spec/setup-tests.ts
spec/simple.spec.ts
src/errors.ts
src/lib/zod-is-type.ts
src/openapi-generator.ts
src/openapi-registry.ts
src/zod-extensions.ts

* Added support for multiple media types for request body and responses
* closes #31 
* closes #34

#31 add support for multiple response media types

---

README.md
spec/types/date.spec.ts
src/lib/zod-is-type.ts
src/openapi-generator.ts
src/zod-extensions.ts

feat: support ZodDate type

---

spec/types/string.spec.ts
src/openapi-generator.ts

Reopening https://github.com/asteasolutions/zod-to-openapi/pull/59 to resolve conflicts and address code changes.

supports minLength/maxLength on string type

---

src/zod-extensions.ts

Resolves #68
Exporting it seems to work.

Fix Typescript 4.9 Error

---

README.md
package-lock.json
package.json
spec/types/string.spec.ts
src/lib/zod-is-type.ts
src/openapi-generator.ts

Heya 🚤 
Since I added this bad boy to Zod, I figured I should be the one to implement it here. Not sure how we want to fix the type support here.
We could extend Zod in this library or we could just bump up the dev deps as this code should work with both versions. Happy with either, just let me know 😄

Add ZodString Datetime support

---

spec/types/discriminated-union.spec.ts
src/openapi-generator.ts

Currently throws an error so this should fix that :)
ps - downloads for this have exploded wew 🚀

Add discriminator mapping for objects using enums as discriminator

---

README.md
spec/modifiers/transform.spec.ts
src/openapi-generator.ts

This adds changes requested for this PR: https://github.com/asteasolutions/zod-to-openapi/pull/121

feat: adds transform

---

spec/types/null.spec.ts
src/openapi-generator.ts
src/v3.0/specifics.ts
src/v3.1/specifics.ts

#139 handle null type based on openapi version

---

spec/routes/parameters.spec.ts
src/zod-extensions.ts

#132 preserve schema metadata for deepPartial

---

spec/types/union.spec.ts
src/openapi-generator.ts

#149 remove unnecessary nullables from schemas

---

src/openapi-registry.ts

provide proper type for responses

---

src/lib/zod-is-type.ts

use _def.typeName for type checking zod schemas

---

spec/routes/parameters.spec.ts
src/openapi-generator.ts
src/openapi-registry.ts

feat: add support for cookies in RouteConfig.request object

---

spec/routes/parameters.spec.ts
src/openapi-generator.ts

feat: combine config.parameters with generated from config.request

---

README.md
package-lock.json
package.json
spec/modifiers/readonly.spec.ts
src/lib/zod-is-type.ts
src/openapi-generator.ts

#173 Added support for ZodReadonly

---

spec/lib/helpers.ts
spec/types/tuple.spec.ts
src/openapi-generator.ts
src/transformers/index.ts
src/transformers/tuple.ts
src/v3.0/specifics.ts
src/v3.1/specifics.ts

handle tuples as prefix items for v3.1.0 of openapi

---

package-lock.json
spec/routes/parameters.spec.ts
src/openapi-generator.ts
src/openapi-registry.ts

Handles #198 and partially #218

Allow effects on objects in request

---

spec/routes/parameters.spec.ts
src/openapi-generator.ts
src/openapi-registry.ts

allow nested effects on parameters

---

README.md

I think everyone has to figure these things on their own right now, so I wanted to add an example on how you can add the extension-method.

Example on how to add the openapi-extension to your code

---

package-lock.json
src/transformers/string.ts

use isDate zod type to create date string on openapi schema
had to upgrade zod, release notes show not breaking changes

Add isDate to string transformer + Zod 3.23.8 upgrade

---

spec/modifiers/custom.spec.ts
spec/modifiers/instanceof.spec.ts
spec/modifiers/refine.spec.ts
src/metadata.ts

#271 handle instance of and custom required fields

---

spec/modifiers/required.spec.ts
src/lib/zod-is-type.ts
src/metadata.ts

#305 added support for required modifier
