asteasolutions/zod-to-openapi

README.md
example/openapi-docs.yml

Tried to make it as to-the-point as possible, moving some examples around. Idea is that potential users would not read as much text and would want to know what this does and supports as quickly as possible. That's why I've put a full-ish example at the top.
Also tried to move some of the boilerplate after the "meat" (e.g. the "generating doc" part in defining routes)

Structure the readme a bit more naturally (hopefully)

---

spec/simple.spec.ts
src/openapi-generator.ts

Handle optional inner types for .default and .refine
Made sure that an externally provided type takes precedence

Handle optional inner types for .default and .refine

---

package-lock.json
package.json

The zod dependency (dev and peer) is now  `^3.0.0` (“Compatible with version” ).
Fixes #23

Make the zod dependency a major version

---

spec/simple.spec.ts
src/openapi-generator.ts

Hey legends, love this library so far. Just a small 🤏 PR to map numbers to integers when `.int()` is used.

Add support for integers

---

src/openapi-generator.ts

Sorry, another quick one 😅 
Allows for some additional keys to be specified while still maintaining type support. Most specifically I need `x-tagGroups` from [redocly](https://redocly.com/docs/api-reference-docs/spec-extensions/) but I imagine other vendors also have some additional keys they use.

Allow for root level specification extensions

---

spec/polymorphism.spec.ts
src/zod-extensions.ts

When I gave something a `refId` and I used `omit` and `pick` on that object. The resulting schema was still trying to use the existing `refId` which is incorrect. This treats new objects created with `.omit` and `.pick` as new objects essentially by clearing the `_def.openapi` from the object. Not sure if there's a better way to do this?

Treat omit/pick as new objects

---

spec/simple.spec.ts
src/openapi-generator.ts

Since an OpenAPI request's underlying `params` and `query` values can only be `string`, it's very common having to resort to `z.preprocess(...)` to convert them to the desired type.
This PR adds support for `z.preprocess(...)`, similarly to the recent addition of support for `refine(...)`.

Support zod preprocessed schemas

---

spec/routes.spec.ts
src/openapi-generator.ts
src/openapi-registry.ts

Hola! :) 
Open API 3.1 added `webhooks` which allow you to define event schema using the same route path objects that you can define paths with.
https://github.com/OAI/OpenAPI-Specification/blob/main/examples/v3.1/webhook-example.yaml
Adding support for Webhooks. I've also tested this on my current project and it produces schema which I validated successfully against the Open API 3.1 schema.

Add webhooks support

---

spec/medatada-overrides.spec.ts
spec/modifiers/nullable.spec.ts
src/lib/lodash.ts
src/openapi-generator.ts

I currently have a small issue where existing metadata on a registered schema gets duplicated when it is referenced. This resolves that issue. In my example budget already contains that description and I never declared it again
Before/After:

fix: ignore existing metadata when referencing registered schema

---

spec/routes.spec.ts
src/openapi-generator.ts

Use the existing `isOptionalSchema` function to calculate if path parameters are optional.

Fix `required` logic for parameters

---

README.md
spec/types/discriminated-union.spec.ts
src/openapi-generator.ts

- Adds the `discriminator` key to discriminated unions generated schema only when a user has registered the schemas.
- Added `mapping` for convenience for the user.
- Change the type of discriminated union to `oneOf`.
https://swagger.io/docs/specification/data-models/inheritance-and-polymorphism/

Add discriminator key to ZodDiscriminatedUnion schemas

---

README.md
example/index.ts
spec/custom-components.spec.ts
spec/lib/helpers.ts
spec/modifiers/nullable.spec.ts
spec/routes.spec.ts
spec/types/discriminated-union.spec.ts
spec/types/intersection.spec.ts
spec/types/union.spec.ts
src/openapi-generator.ts

The generator's constructor now takes a mandatory Open API version. This is required in order to drive different generation behaviour based on the version.
`generateDocument` no longer takes a `openapi` version and instead we will use the version from the generator's constructor to populate this field.
Open API 3.1.0 made `nullable` an invalid key and instead chose to become JSON Schema compatible by using a type array with `null` inside it. The problem here is that the `type` array is invalid in previous versions.
https://www.openapis.org/blog/2021/02/16/migrating-from-openapi-3-0-to-3-1-0
Also adds nullable support for:
- Union
- Discriminated Union
- Intersection
- Array
- Record

Open API 3.1.0 Support

---

spec/routes.spec.ts
src/lib/zod-is-type.ts
src/openapi-generator.ts
src/openapi-registry.ts

Currently the ZodObject<any> type defaults the second value to "strip" which means that "strict" types are not supported.
Substitute usage of `ZodObject<any>` with `AnyZodObject` type.

Fix Route types to support strict objects

---

spec/types/object.spec.ts
src/openapi-generator.ts

According to the [Open API Specification](https://swagger.io/specification/):
>additionalProperties - Value can be boolean or object. Inline or referenced schema MUST be of a [Schema Object](https://swagger.io/specification/#schema-object) and not a standard JSON Schema. Consistent with JSON Schema, additionalProperties **defaults to true**.
According to the [Zod Readme](https://github.com/colinhacks/zod#passthrough):
>.passthrough
**By default** Zod object schemas strip out unrecognized keys during parsing.
This means that we should see alot more of this in the schema if this bit of the code was working:
Since this defaults to true we don't need this passthrough code. Instead I'll add the option to map strict objects.

feat: Add strict object additionalProperties: false mapping

---

package-lock.json
package.json

Resolves #81
This is a *Breaking Change*.
Zod [introduced a breaking change](https://github.com/colinhacks/zod/pull/1290#issuecomment-1347912219) to their types in `3.20` which is incompatible with previous versions of this library. This bumps up the peerDependency version of Zod to `3.20.2`

Bump Zod Version

---

spec/types/native-enum.spec.ts
src/openapi-generator.ts

For example, if I use 'openapi-generator for php' to automatically generate a .php file from 'openapi-docs.yml', the 'nativeEnum' part is converted to PHP's float type.
Normally, numeric Enums should be of type int, not float.

For 'nativeEnum', should be 'type: integer', not 'type: number

---

src/openapi-registry.ts

Thank you for maintaining this excellent repository! I'm working on a project that uses the OPTIONS verb and needed to expand the list of available methods. Cheers.
`type Method = 'get' | 'post' | 'put' | 'delete' | 'patch' | 'head' | 'options' | 'trace';`

Add 'head', 'options', and 'trace' to Method type in OpenAPI registry

---

README.md
spec/modifiers/pipe.spec.ts
src/lib/zod-is-type.ts
src/openapi-generator.ts

Based on the [documentation](https://zod.dev/?id=pipe) it seems that we can generate a documentation for `ZodPipeline`.
However we do have two options:
1. Use the `in` property saved within the zod schema (done in the PR). My thought process was that this is what an API would receive when this schema is used for validation.
2. Use the `out` property as it describes the target state (might not always be the case).
Overall I feel like `in` is the only correct option we can use. But saying that it does bring up the question why cannot we just use the same logic when handling the result of `.transform()`. @georgyangelov any thoughts would be appreciated.

#115 added support for ZodPipeline

---

spec/routes/index.spec.ts
src/openapi-generator.ts
src/openapi-registry.ts

Resolves #116.
Side note: right now there are 3 approaches to generate response headers:
1. Directly specifying a `HeadersObject` through the response 
```
responses: {
204: {
description: 'Success',
headers: { 'Set-Cookie': { schema: { type: 'string' } } },
},
},
```
2. Using custom components:
```
const apiKeyHeader = registry.registerComponent('headers', 'api-key', {
example: '1234',
required: true,
});
// ...
responses: {
200: { description: 'Sample response', headers: { 'x-api-key': apiKeyHeader.ref }  }
};
```
3. Using ZodObject:
```
responses: {
204: {
description: 'Success',
headers: z.object({
'Set-Cookie': z.string().openapi({ example: 'token=test' }),
}),
},
},
```
However I do feel that all are valid because:
1. Obviouslly we should allow plain documentation to be written as …

added support for zod object for response headers

---

package.json

When I ran `npm install --package-lock git+https://github.com/asteasolutions/zod-to-openapi.git#5c9ae89` to use the latest code changes, it does not install js files, so my code fails with:
```
Error: Cannot find module '/Users/user/app/node_modules/@asteasolutions/zod-to-openapi/dist/index.js'. Please verify that the package.json has a valid "main" entry
```
This fix adds a `prepare` script to run `npm run build`.

prepare script to build when npm install from git

---

spec/lib/helpers.ts
src/openapi-generator.ts
src/openapi-metadata.ts
src/openapi-registry.ts
src/zod-extensions.ts

As specified here https://zod.dev/?id=writing-generic-functions `ZodTypeAny` is a better way to handle a generic schema parameter compared to `ZodSchema<any>`.
This PR is also needed to allow smoother interoperability between this and other libraries that manipulate the default `Zod` types

Use ZodTypeAny instead of ZodSchema<any>

---

src/index.ts

These exports seem wrong, you can just import directly from the `openapi3-ts` dependency without going through this library.
On top of that, they are actually the source of an error when using this project as a dependency in a `yarn` project:
```
Module not found: Can't resolve 'openapi3-ts/oas30' in '[...]/node_modules/@asteasolutions/zod-to-openapi/dist'
```
I believe it's safe to remove them, was there any specific reason why they were added?

Remove openapi3-ts exports

---

spec/modifiers/deepPartial.spec.ts
src/zod-extensions.ts

fixed deepPartial modifier preserving refId

---

src/zod-extensions.ts

As mentionend in #189 
I ran the tests and they all ran fine.
Let me know if there are any issues with this

make examples use both input and output types of zod

---

src/openapi-registry.ts

I've improve the type of ZodContentObject to provide autocompletion with most common media type without restricting the ability to put any string you want.

add autocompletion for media type

---

spec/types/record.spec.ts
src/lib/lodash.ts
src/openapi-generator.ts

handle enums as keys for zod records

---

.github/workflows/check.yml
package-lock.json
package.json
rollup.config.mjs
src/transformers/index.ts
tsconfig.build.json
tsconfig.json

Alternative approach to ESM modules using Rollup as dev dependency

export ESM modules with rollup

---

README.md

Since https://github.com/asteasolutions/zod-to-openapi/pull/71 it has been possible to support `strict` mode on Zod objects, however, I couldn't find this easily in the docs.
Adding this to make it clear that by default `additionalProperties` will be set to `true`, as this may catch others out.
Happy to reword, move docs about as required.

docs: update to include information about strict usage on an object

---

src/zod-extensions.ts

check for missing _internal when extending a non registered schema
